# Generated by Django 4.2.19 on 2025-02-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_galleryimage_subscription_alter_destination_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
