# Generated by Django 4.2.19 on 2025-02-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_galleryimage_delete_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='description',
        ),
        migrations.AddField(
            model_name='destination',
            name='state',
            field=models.CharField(default='Gujarat', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
    ]
