# Generated by Django 4.2.19 on 2025-02-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_destination_description_destination_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
