# Generated by Django 4.2.19 on 2025-02-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_view360_latitude_view360_longitude_view360_pano_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view360',
            old_name='image',
            new_name='panorama_image',
        ),
    ]
