# Generated by Django 4.2.19 on 2025-02-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_image_view360_panorama_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view360',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='view360',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='view360',
            name='pano_id',
        ),
        migrations.AddField(
            model_name='view360',
            name='iframe_url',
            field=models.URLField(blank=True, help_text='Google Maps Embed URL for Street View', max_length=1000, null=True),
        ),
    ]
