# Generated by Django 4.2.19 on 2025-03-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0020_remove_profile_id_alter_profile_user'),
        ('main', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AUTH.profile'),
            preserve_default=False,
        ),
    ]
