# Generated by Django 4.2.19 on 2025-04-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_review_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('beach', 'Beach'), ('heritage', 'Heritage'), ('wildlife', 'Wildlife'), ('religious', 'Religious'), ('adventure', 'Adventure'), ('hill_station', 'Hill Station'), ('city', 'City')], default='city', max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
