# Generated by Django 4.2.19 on 2025-04-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_destination_options_destination_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={},
        ),
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('beach', 'Beach'), ('heritage', 'Heritage'), ('wildlife', 'Wildlife'), ('religious', 'Religious'), ('adventure', 'Adventure'), ('hill_station', 'Hill Station')], default='city', max_length=50),
        ),
    ]
