# Generated by Django 4.2.19 on 2025-04-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_destination_options_alter_destination_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='category',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='created_at',
        ),
    ]
