# Generated by Django 4.2.19 on 2025-04-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_destination_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('beach', 'Beach'), ('heritage', 'Heritage'), ('wildlife', 'Wildlife'), ('religious', 'Religious'), ('adventure', 'Adventure'), ('hill_station', 'Hill Station')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
