# Generated by Django 4.2.19 on 2025-04-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_destination_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('beach', 'Beach'), ('heritage', 'Heritage'), ('wildlife', 'Wildlife'), ('religious', 'Religious'), ('adventure', 'Adventure'), ('hill_station', 'Hill Station')], default='beach', max_length=50),
        ),
    ]
