# Generated by Django 4.2.19 on 2025-02-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0004_profile_country_code_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country_code',
            field=models.CharField(blank=True, default='+1', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
