# Generated by Django 4.2.19 on 2025-02-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0005_alter_profile_country_code_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='Unknown', max_length=15, null=True),
        ),
    ]
