# Generated by Django 4.2.19 on 2025-02-26 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0014_alter_profile_first_name_alter_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='number',
            new_name='house_no',
        ),
    ]
