# Generated by Django 4.2.19 on 2025-02-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0015_rename_number_profile_house_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country_code',
            field=models.CharField(blank=True, default='+91', max_length=5, null=True),
        ),
    ]
