# Generated by Django 4.2.19 on 2025-02-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0016_alter_profile_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
